definitions:
  handlers.countryResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Country'
        type: array
    type: object
  handlers.errResponse:
    properties:
      message:
        type: string
    type: object
  handlers.userResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.User'
        type: array
    type: object
  model.Country:
    properties:
      name:
        type: string
    type: object
  model.User:
    properties:
      email:
        type: string
      fullName:
        type: string
      isActive:
        type: boolean
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Sample description
  title: Simple API
  version: "1"
paths:
  /countries/all:
    get:
      description: get all countries
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.countryResponse'
      summary: get all countries
      tags:
      - Countries
  /users:
    post:
      consumes:
      - application/json
      description: create new user
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errResponse'
      summary: create a new user
      tags:
      - Users
  /users/all:
    get:
      description: get all users
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.userResponse'
      summary: return list of all users
      tags:
      - Users
swagger: "2.0"
